name: julien
description: "Data Migration Client."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  async: any
  collection: any
  intl: any
  meta: any

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.28.0

  # BLoC
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  # Networking
  http: ^1.2.2
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1

  # Storing data
  shared_preferences: ^2.3.2

  # Routing
  go_router: ^14.3.0

  # Logging
  stack_trace: ^1.11.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

  # Utils
  clock: ^1.1.1
  cupertino_icons: ^1.0.8
  intercepted_client: ^0.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  platform_info: ^5.0.0
  sentry_flutter: ^8.9.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  equatable: ^2.0.5

dev_dependencies:
  # Testing
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Utils
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  # Codegen
  build_runner: ^2.4.12
  dart_code_metrics_presets: ^2.16.0

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CaskaydiaCove
      fonts:
        - asset: assets/fonts/CaskaydiaCoveNerdFont-Bold.ttf
        - asset: assets/fonts/CaskaydiaCoveNerdFont-Bold.ttf
        - asset: assets/fonts/CaskaydiaCoveNerdFont-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
